<?php

use craft\db\Query;
use craft\fieldlayoutelements\CustomField;
use craft\fields\PlainText;
use craft\helpers\Json;
use craft\helpers\StringHelper;
use craft\models\FieldLayout;
use craft\models\FieldLayoutTab;
use Tests\Support\Fixtures\VizyFixtureFactory;
use verbb\hyper\content\ModifyOptions;
use verbb\hyper\fields\HyperField;
use verbb\hyper\Hyper;
use verbb\hyper\links\Url;
use verbb\hyper\migrations\MigrateTypedLinkContent;
use verbb\vizy\content\Change;
use verbb\vizy\fields\VizyField;
use verbb\vizy\models\BlockType;
use verbb\vizy\Vizy;

it('composes both current plugin APIs and migrates Hyper through Vizy without synthetic relations', function() {
    expect(class_exists(Hyper::class))->toBeTrue();
    if (!Craft::$app->plugins->isPluginInstalled('hyper')) Craft::$app->plugins->installPlugin('hyper');
    $suffix = StringHelper::randomString(8);
    $target = new PlainText(['name' => 'Leaf', 'handle' => 'leaf' . $suffix]);
    Craft::$app->fields->saveField($target);
    $vizy = new VizyField(['name' => 'Body', 'handle' => 'body' . $suffix]);
    Craft::$app->fields->saveField($vizy);
    $hyper = new HyperField(['name' => 'Links', 'handle' => 'links' . $suffix]);
    $url = new Url(['handle' => 'url', 'enabled' => true]);
    $linkLayout = new FieldLayout(['type' => Url::class]);
    $v = new CustomField($vizy, ['uid' => StringHelper::UUID()]);
    $hLeaf = new CustomField($target, ['uid' => StringHelper::UUID()]);
    $linkLayout->setTabs([new FieldLayoutTab(['name' => 'Content', 'layout' => $linkLayout, 'elements' => [$v, $hLeaf]])]);
    $url->setFieldLayout($linkLayout);
    $hyper->enableCustomLinkTypes();
    $hyper->setLinkTypes([$url->getSettingsConfigForDb()]);
    expect(Craft::$app->fields->saveField($hyper))->toBeTrue();
    $blockLayout = new FieldLayout(['type' => verbb\vizy\elements\Block::class]);
    $h = new CustomField($hyper, ['uid' => StringHelper::UUID()]);
    $vLeaf = new CustomField($target, ['uid' => StringHelper::UUID()]);
    $blockLayout->setTabs([new FieldLayoutTab(['name' => 'Content', 'layout' => $blockLayout, 'elements' => [$h, $vLeaf]])]);
    $type = new BlockType(['uid' => StringHelper::UUID(), 'name' => 'Mixed', 'handle' => 'mixed' . $suffix]);
    $type->setFieldLayout($blockLayout);
    expect(Vizy::$plugin->getBlockTypes()->saveBlockType($type))->toBeTrue();
    $doc = fn($slots) => ['type' => 'doc', 'attrs' => ['schemaVersion' => 2], 'content' => [['type' => 'vizyBlock', 'attrs' => ['blockUid' => StringHelper::UUID(), 'blockTypeUid' => $type->uid, 'enabled' => true, 'fieldSlots' => $slots]]]];
    $links = fn($fields) => [['uid' => StringHelper::UUID(), 'linkTypeHandle' => 'url', 'linkValue' => 'https://example.test', 'fields' => $fields]];
    $value = $doc([$h->uid => $links([$v->uid => Json::encode($doc([$vLeaf->uid => 'deep'])), $hLeaf->uid => 'link-leaf']), $vLeaf->uid => 'outer']);
    $map = Vizy::$plugin->getContent()->captureFieldLocations($target->uid);
    $contexts = [];
    $callback = function($raw, $ctx) use (&$contexts) { $contexts[] = $ctx; return Change::replace(strtoupper($raw)); };
    $viaVizy = Vizy::$plugin->getContent()->transformValue($value, $vizy->uid, $map, $callback);
    $viaHyper = Hyper::$plugin->getContent()->transformValue($value, $vizy->uid, $map, $callback);
    expect($viaVizy)->toBe($viaHyper)->and($viaVizy['changed'])->toBe(3);
    expect($contexts[0]['path'])->toHaveCount(3)->and($contexts[0]['hasDurableOwner'])->toBeFalse();
    $reverse = Hyper::$plugin->getContent()->transformValue($links([$v->uid => $value]), $hyper->uid, $map, $callback);
    expect($reverse['changed'])->toBe(3);

    $owner = VizyFixtureFactory::entry('Hyper consumer');
    $layout = $owner->getFieldLayout();
    $tab = $layout->getTabs()[0];
    $root = new CustomField($vizy, ['uid' => StringHelper::UUID()]);
    $tab->setElements([...$tab->getElements(), $root]);
    Craft::$app->fields->saveLayout($layout);
    $source = $doc([$h->uid => ['type' => 'url', 'value' => 'https://example.test/typed', 'customText' => 'Retained']]);
    $where = ['elementId' => $owner->id, 'siteId' => $owner->siteId];
    Craft::$app->db->createCommand()->update('{{%elements_sites}}', ['content' => new yii\db\JsonExpression([$root->uid => Json::encode($source)])], $where)->execute();
    $read = fn() => (new Query())->select('content')->from('{{%elements_sites}}')->where($where)->scalar();
    $before = $read();
    $migration = new MigrateTypedLinkContent();
    $migration->dryRun = true;
    $migration->migrateVizyContent(['id' => $hyper->id], $hyper);
    expect($read())->toBe($before);
    $migration->dryRun = false;
    $migration->migrateVizyContent(['id' => $hyper->id], $hyper);
    $after = $read();
    $saved = Json::decode(Json::decode($after)[$root->uid]);
    expect($saved['content'][0]['attrs']['fieldSlots'][$h->uid][0]['linkValue'])->toBe('https://example.test/typed');
    $migration->migrateVizyContent(['id' => $hyper->id], $hyper);
    expect($read())->toBe($after);
    expect((int)(new Query())->from('{{%hyper_links}}')->where(['ownerId' => $owner->id])->count())->toBe(0);
})->group('content-api-integration');
